# Generated by Django 3.1.2 on 2020-11-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20201114_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='description',
            new_name='title',
        ),
    ]
