# Generated by Django 3.1.2 on 2020-11-28 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_lookup_id'),
        ('finances', '0003_auto_20201114_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_expense', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_expense', to='projects.task'),
        ),
    ]
