# Generated by Django 3.1.2 on 2020-11-11 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lookup_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
