# Generated by Django 3.1.2 on 2020-11-28 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animallog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 5, 42, 49, 315174, tzinfo=utc)),
        ),
    ]
