# Generated by Django 3.1.2 on 2020-11-28 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_auto_20201128_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animallog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 5, 46, 46, 733667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meattype',
            name='style',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
