# Generated by Django 3.1.2 on 2020-11-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_auto_20201128_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meattype',
            name='style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
