# Generated by Django 3.1.2 on 2020-12-03 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_auto_20201128_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalharvest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
